// Drizzle schema for TractionOS.
//
// Conventions:
//   - UUID primary keys, generated by Postgres (`gen_random_uuid()`).
//   - All timestamps are `timestamp with time zone`; everything stored UTC.
//   - Percentages live as decimals on `numeric` columns (0.50, not 50). Currency
//     stays in cents on the column (integer dollars passed through ×100 on the
//     write path). See `docs/kpi-definitions.md` for the full convention.
//   - Every domain row carries a single `orgId` — there is no parent org and no
//     `orgIds` array. See ADR-0009.
//   - Indexes target the common access paths: filter-by-org, filter-by-owner,
//     filter-by-week, and the per-week-per-measurable uniqueness on entries.

import { sql } from "drizzle-orm";
import {
  pgEnum,
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  numeric,
  boolean,
  jsonb,
  date,
  index,
  uniqueIndex,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";

// ─────────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────────

export const personRole = pgEnum("person_role", ["admin", "member", "viewer"]);

export const goalDirection = pgEnum("goal_direction", [
  "gte",
  "lte",
  "eq",
  "between",
  "trend_down",
  "trend_up",
]);

export const cadence = pgEnum("cadence", ["weekly", "monthly"]);

export const statusColor = pgEnum("status_color", ["green", "yellow", "red"]);

export const entrySource = pgEnum("entry_source", [
  "manual",
  "voice",
  "fireflies",
  "teams_native",
  "transcript_manual",
  "system",
]);

export const noteClassification = pgEnum("note_classification", [
  "explained_one_off",
  "structural_issue",
  "on_plan_to_recover",
  "no_context",
]);

export const rockStatus = pgEnum("rock_status", [
  "on_track",
  "off_track",
  "completed",
]);

export const todoStatus = pgEnum("todo_status", [
  "open",
  "done",
  "rolled_over",
  "dropped",
]);

export const issuePriority = pgEnum("issue_priority", [
  "critical",
  "high",
  "medium",
  "low",
]);

export const issueStatus = pgEnum("issue_status", [
  "open",
  "ids_in_progress",
  "resolved",
  "tabled",
]);

export const meetingStatus = pgEnum("meeting_status", [
  "scheduled",
  "live",
  "concluded",
]);

// ─────────────────────────────────────────────────────────────────────────────
// Organizations & People
// ─────────────────────────────────────────────────────────────────────────────
// Clerk owns identity + memberships. Our rows mirror just enough to enable
// queries (joins, filters, foreign keys). The seed script provisions Clerk
// orgs and members; here we store the local row that local queries reference.

export const organizations = pgTable(
  "organizations",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    clerkOrgId: text("clerk_org_id").notNull(),
    name: text("name").notNull(),
    code: text("code").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    clerkOrgIdUnique: uniqueIndex("organizations_clerk_org_id_unique").on(
      t.clerkOrgId,
    ),
    codeUnique: uniqueIndex("organizations_code_unique").on(t.code),
  }),
);

export const people = pgTable(
  "people",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    clerkUserId: text("clerk_user_id").notNull(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    avatarUrl: text("avatar_url"),
    defaultOrgId: uuid("default_org_id").references(() => organizations.id),
    // Role is a sensible default; per-org role is governed by Clerk membership.
    // Stored here so that simple admin checks don't require a round trip.
    role: personRole("role").notNull().default("member"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    clerkUserIdUnique: uniqueIndex("people_clerk_user_id_unique").on(
      t.clerkUserId,
    ),
    emailIdx: index("people_email_idx").on(t.email),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Scorecard
// ─────────────────────────────────────────────────────────────────────────────

export const measurables = pgTable(
  "measurables",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    name: text("name").notNull(),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => people.id),
    unit: text("unit"), // free-form, e.g. "USD", "days", "%"
    formatHint: text("format_hint"), // one of: currency_usd|percent|days|turns|count|currency_usd_trend
    goalDirection: goalDirection("goal_direction").notNull(),
    goalValue: numeric("goal_value", { precision: 18, scale: 6 }),
    goalSecondary: numeric("goal_secondary", { precision: 18, scale: 6 }),
    cadence: cadence("cadence").notNull().default("weekly"),
    formula: text("formula"), // human-readable; displayed in tooltips
    displayOrder: integer("display_order").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orgIdx: index("measurables_org_idx").on(t.orgId),
    ownerIdx: index("measurables_owner_idx").on(t.ownerId),
    orgDisplayOrderIdx: index("measurables_org_display_order_idx").on(
      t.orgId,
      t.displayOrder,
    ),
  }),
);

export const weeks = pgTable(
  "weeks",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    weekEndingDate: date("week_ending_date").notNull(),
    weekNumber: integer("week_number").notNull(), // ISO week number
    quarter: text("quarter").notNull(), // e.g. "Q2 2026"
    fiscalYear: integer("fiscal_year").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    weekEndingDateUnique: uniqueIndex("weeks_week_ending_date_unique").on(
      t.weekEndingDate,
    ),
  }),
);

export const entries = pgTable(
  "entries",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    measurableId: uuid("measurable_id")
      .notNull()
      .references(() => measurables.id),
    weekId: uuid("week_id")
      .notNull()
      .references(() => weeks.id),
    actual: numeric("actual", { precision: 18, scale: 6 }),
    note: text("note"),
    statusOverride: statusColor("status_override"),
    // The shading engine's cached note classification (see
    // .claude/agents/note-classifier.md). Recomputed when `note` changes.
    noteClassification: noteClassification("note_classification"),
    // 0..1, set when the source isn't manual (voice or transcript).
    confidence: numeric("confidence", { precision: 5, scale: 4 }),
    source: entrySource("source").notNull().default("manual"),
    enteredByPersonId: uuid("entered_by_person_id").references(() => people.id),
    // When the source includes diarization (Fireflies, Teams native),
    // this is the speaker the platform attributed the change to.
    attributedToPersonId: uuid("attributed_to_person_id").references(
      () => people.id,
    ),
    enteredAt: timestamp("entered_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    measurableWeekUnique: uniqueIndex("entries_measurable_week_unique").on(
      t.measurableId,
      t.weekId,
    ),
    weekIdx: index("entries_week_idx").on(t.weekId),
    enteredByIdx: index("entries_entered_by_idx").on(t.enteredByPersonId),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Rocks
// ─────────────────────────────────────────────────────────────────────────────

export const rocks = pgTable(
  "rocks",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    description: text("description").notNull(),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => people.id),
    quarter: text("quarter").notNull(), // e.g. "Q2 2026"
    dueDate: date("due_date"),
    status: rockStatus("status").notNull().default("on_track"),
    // Append-only: [{ date, status, note, changedByPersonId }]
    statusHistory: jsonb("status_history").notNull().default(sql`'[]'::jsonb`),
    notes: text("notes"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orgIdx: index("rocks_org_idx").on(t.orgId),
    ownerIdx: index("rocks_owner_idx").on(t.ownerId),
    orgQuarterIdx: index("rocks_org_quarter_idx").on(t.orgId, t.quarter),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Issues (declared before todos because todos.parentIssueId references it)
// ─────────────────────────────────────────────────────────────────────────────

export const issues = pgTable(
  "issues",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    title: text("title").notNull(),
    priority: issuePriority("priority").notNull().default("medium"),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => people.id),
    rootCause: text("root_cause"),
    resolution: text("resolution"),
    status: issueStatus("status").notNull().default("open"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  },
  (t) => ({
    orgIdx: index("issues_org_idx").on(t.orgId),
    ownerIdx: index("issues_owner_idx").on(t.ownerId),
    orgStatusIdx: index("issues_org_status_idx").on(t.orgId, t.status),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Meetings (referenced by todos and transcripts)
// ─────────────────────────────────────────────────────────────────────────────

export const meetings = pgTable(
  "meetings",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    scheduledFor: timestamp("scheduled_for", { withTimezone: true }).notNull(),
    facilitatorId: uuid("facilitator_id")
      .notNull()
      .references(() => people.id),
    scribeId: uuid("scribe_id").references(() => people.id),
    meetingNumber: integer("meeting_number"),
    quarter: text("quarter").notNull(),
    status: meetingStatus("status").notNull().default("scheduled"),
    rating: numeric("rating", { precision: 3, scale: 1 }), // 1.0..10.0 (per-attendee avg)
    notes: text("notes"),
    cascadingMessages: text("cascading_messages"),
    liveblocksRoomId: text("liveblocks_room_id"),
    linkedTeamsMeetingId: text("linked_teams_meeting_id"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    concludedAt: timestamp("concluded_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orgIdx: index("meetings_org_idx").on(t.orgId),
    orgScheduledIdx: index("meetings_org_scheduled_idx").on(
      t.orgId,
      t.scheduledFor,
    ),
    liveblocksRoomIdUnique: uniqueIndex(
      "meetings_liveblocks_room_id_unique",
    ).on(t.liveblocksRoomId),
    teamsMeetingIdUnique: uniqueIndex(
      "meetings_linked_teams_meeting_id_unique",
    ).on(t.linkedTeamsMeetingId),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// To-Dos
// ─────────────────────────────────────────────────────────────────────────────

export const todos = pgTable(
  "todos",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    description: text("description").notNull(),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => people.id),
    dueDate: date("due_date"),
    status: todoStatus("status").notNull().default("open"),
    rolloverCount: integer("rollover_count").notNull().default(0),
    parentTodoId: uuid("parent_todo_id").references(
      (): AnyPgColumn => todos.id,
    ),
    createdInMeetingId: uuid("created_in_meeting_id").references(
      () => meetings.id,
    ),
    completedInMeetingId: uuid("completed_in_meeting_id").references(
      () => meetings.id,
    ),
    parentIssueId: uuid("parent_issue_id").references(() => issues.id),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orgIdx: index("todos_org_idx").on(t.orgId),
    ownerIdx: index("todos_owner_idx").on(t.ownerId),
    orgStatusIdx: index("todos_org_status_idx").on(t.orgId, t.status),
    parentIssueIdx: index("todos_parent_issue_idx").on(t.parentIssueId),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Meeting attendees & transcripts
// ─────────────────────────────────────────────────────────────────────────────

export const meetingAttendees = pgTable(
  "meeting_attendees",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    meetingId: uuid("meeting_id")
      .notNull()
      .references(() => meetings.id),
    personId: uuid("person_id")
      .notNull()
      .references(() => people.id),
    present: boolean("present").notNull().default(false),
    rating: integer("rating"), // 1..10, set on conclude
  },
  (t) => ({
    meetingPersonUnique: uniqueIndex("meeting_attendees_meeting_person_unique").on(
      t.meetingId,
      t.personId,
    ),
    meetingIdx: index("meeting_attendees_meeting_idx").on(t.meetingId),
  }),
);

export const transcripts = pgTable(
  "transcripts",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    meetingId: uuid("meeting_id")
      .notNull()
      .references(() => meetings.id),
    source: entrySource("source").notNull(), // 'fireflies' | 'teams_native' | 'transcript_manual'
    rawText: text("raw_text").notNull(),
    // Normalized utterances: [{ speaker, text, ts }]
    utterances: jsonb("utterances"),
    durationSec: integer("duration_sec"),
    summary: text("summary"),
    extractedJson: jsonb("extracted_json"),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    meetingIdx: index("transcripts_meeting_idx").on(t.meetingId),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Week snapshots (`/snapshot-week`)
// ─────────────────────────────────────────────────────────────────────────────
// Snapshots are append-only — `--force` writes a new version, preserving older
// ones. The frozen payload includes computed status so future re-renders don't
// drift if the shading engine evolves.

export const weekSnapshots = pgTable(
  "week_snapshots",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    weekId: uuid("week_id")
      .notNull()
      .references(() => weeks.id),
    takenByPersonId: uuid("taken_by_person_id").references(() => people.id),
    // Frozen `entries` for the week, plus the computed status per entry at
    // snapshot time. Shape:
    //   [{ entryId, measurableId, actual, note, status, intensity, reason }]
    payload: jsonb("payload").notNull(),
    snapshotAt: timestamp("snapshot_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orgWeekIdx: index("week_snapshots_org_week_idx").on(t.orgId, t.weekId),
    orgWeekSnapshotAtIdx: index("week_snapshots_org_week_snapshot_at_idx").on(
      t.orgId,
      t.weekId,
      t.snapshotAt,
    ),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Audit log
// ─────────────────────────────────────────────────────────────────────────────
// Every write — manual, voice, transcript — writes here. See docs/permissions.md
// §"The write contract" for the invariant.

export const auditLog = pgTable(
  "audit_log",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id").references(() => organizations.id),
    personId: uuid("person_id").references(() => people.id),
    action: text("action").notNull(), // verb, e.g. "update_actual", "complete_todo"
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id"),
    before: jsonb("before"),
    after: jsonb("after"),
    source: entrySource("source").notNull(),
    attributedToPersonId: uuid("attributed_to_person_id").references(
      () => people.id,
    ),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orgIdx: index("audit_log_org_idx").on(t.orgId),
    entityIdx: index("audit_log_entity_idx").on(t.entityType, t.entityId),
    personIdx: index("audit_log_person_idx").on(t.personId),
    createdAtIdx: index("audit_log_created_at_idx").on(t.createdAt),
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Type helpers — inferred row types for use in queries / server actions.
// ─────────────────────────────────────────────────────────────────────────────

export type Organization = typeof organizations.$inferSelect;
export type NewOrganization = typeof organizations.$inferInsert;

export type Person = typeof people.$inferSelect;
export type NewPerson = typeof people.$inferInsert;

export type Measurable = typeof measurables.$inferSelect;
export type NewMeasurable = typeof measurables.$inferInsert;

export type Week = typeof weeks.$inferSelect;
export type NewWeek = typeof weeks.$inferInsert;

export type Entry = typeof entries.$inferSelect;
export type NewEntry = typeof entries.$inferInsert;

export type Rock = typeof rocks.$inferSelect;
export type NewRock = typeof rocks.$inferInsert;

export type Todo = typeof todos.$inferSelect;
export type NewTodo = typeof todos.$inferInsert;

export type Issue = typeof issues.$inferSelect;
export type NewIssue = typeof issues.$inferInsert;

export type Meeting = typeof meetings.$inferSelect;
export type NewMeeting = typeof meetings.$inferInsert;

export type MeetingAttendee = typeof meetingAttendees.$inferSelect;
export type NewMeetingAttendee = typeof meetingAttendees.$inferInsert;

export type Transcript = typeof transcripts.$inferSelect;
export type NewTranscript = typeof transcripts.$inferInsert;

export type WeekSnapshot = typeof weekSnapshots.$inferSelect;
export type NewWeekSnapshot = typeof weekSnapshots.$inferInsert;

export type AuditLogEntry = typeof auditLog.$inferSelect;
export type NewAuditLogEntry = typeof auditLog.$inferInsert;
